---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question

1. Use backward elimination, forward selection and stepwise regression to select a subset of model. 

2. Write down the final model chosen by these three procedures. 

## Useful R outputs

### Output 1

```{r, comment=NA, message=FALSE, warning=FALSE, echo=FALSE}
y <- c(11.9, 22.8, 18.7, 20.1, 12.9, 21.7, 27.1, 25.4, 21.3, 19.3, 25.4, 27.2, 
       11.7, 17.8, 12.8, 23.9, 22.6, 25.4, 14.8, 21.1)
x1 <- c(19.5, 24.7, 30.7, 29.8, 19.1, 25.6, 31.4, 27.9, 22.1, 25.5, 
        31.1, 30.4, 18.7, 19.7, 14.6, 29.5, 27.7, 30.2, 22.7, 25.2)
x2 <- c(43.1, 49.8, 51.9, 54.3, 42.2, 53.9, 58.5, 52.1, 49.9, 53.5,
        56.6, 56.7, 46.5, 44.2, 42.7, 54.4, 55.3, 58.6, 48.2, 51.0)
x3 <- c(29.1, 28.2, 37.0, 31.1, 30.9, 23.7, 27.6, 30.6, 23.2, 24.8,
        30.0, 28.3, 23.0, 28.6, 21.3, 30.1, 25.7, 24.6, 27.1, 27.5)
data <- data.frame(Y=y, x1=x1, x2=x2, x3=x3)
data
```

### Output 2

```{r, comment=NA, message=FALSE}
library(GGally)
ggpairs(data)
```

### Output 3


```{r, comment=NA, message=FALSE}
lm.minimal <- lm(Y ~ 1, data=data)
lm.minimal
```

### Output 4



```{r, comment=NA, message=FALSE, warning=FALSE}
lm.all <- lm(Y ~ . , data=data)
lm.all
```


### Output 5


```{r, comment=NA, message=FALSE}
step(lm.minimal, scope=list(upper = lm.all,
lower= lm.minimal), direction="forward",
trace=1)
```

### Output 6


```{r, comment=NA, message=FALSE}
step(lm.all, direction="backward", trace=1)
```

### Output 7


```{r, comment=NA, message=FALSE}
step(lm.minimal, scope=list(upper = lm.all,
lower= lm.minimal),  direction="both", trace=1)
```